sudo: required
language: java
jdk: oraclejdk11

node_js:
  - "10"

services:
  - postgresql

before_install:
  - chmod +x mvnw
  - sudo apt-get install nodejs

addons:
  sonarcloud:
  organization: "ivanmrsulja"
  token: $SONAR_TOKEN

script:
  - ./mvnw clean install -DskipTests=false -B
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=ivanmrsulja_isamrs-deploy


dist: trusty

deploy:
  provider: heroku
  api_key: $HEROKU_API_KEY
  app: isamrs2021-tim6